root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/gateway.exe ./cmd/gateway"
entrypoint = ["./tmp/gateway.exe"]
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["tmp", "vendor", "database"]
delay = 1000
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true